onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/aclk}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/aresetn}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awaddr}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awlen}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awburst}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awsize}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awvalid}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wdata}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wstrb}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wlast}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wvalid}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/bresp}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/bvalid}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/bready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/araddr}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arlen}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arburst}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arsize}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arvalid}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/rdata}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/rresp}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/rlast}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/rvalid}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/rready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awvalid_ready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awaddr_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awlen_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/awsize_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/w_addr}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/w_beat_cnt}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/w_beat_cnt_en}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/mem_wr_data}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/mem_wr_strb}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/mem_wr_en}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/wlast_done}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arvalid_ready}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/araddr_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arlen_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/arsize_s}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/r_addr}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/r_beat_cnt}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/r_beat_cnt_en}
add wave -noupdate -group axi_slave_1 {/axi_top_1m3s_tb/dut/gen_slaves[2]/u_slave/mem_rd_data}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/aclk}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/aresetn}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awaddr}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awlen}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awburst}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awsize}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awvalid}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wdata}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wstrb}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wlast}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wvalid}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/bresp}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/bvalid}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/bready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/araddr}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arlen}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arburst}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arsize}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arvalid}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/rdata}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/rresp}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/rlast}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/rvalid}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/rready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awvalid_ready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awaddr_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awlen_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/awsize_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/w_addr}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/w_beat_cnt}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/w_beat_cnt_en}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/mem_wr_data}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/mem_wr_strb}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/mem_wr_en}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/wlast_done}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arvalid_ready}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/araddr_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arlen_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/arsize_s}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/r_addr}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/r_beat_cnt}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/r_beat_cnt_en}
add wave -noupdate -group axi_slave_2 {/axi_top_1m3s_tb/dut/gen_slaves[1]/u_slave/mem_rd_data}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/aclk}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/aresetn}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awaddr}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awlen}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awburst}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awsize}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awvalid}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wdata}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wstrb}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wlast}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wvalid}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/bresp}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/bvalid}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/bready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/araddr}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arlen}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arburst}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arsize}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arvalid}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/rdata}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/rresp}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/rlast}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/rvalid}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/rready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awvalid_ready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awaddr_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awlen_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/awsize_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/w_addr}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/w_beat_cnt}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/w_beat_cnt_en}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/mem_wr_data}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/mem_wr_strb}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/mem_wr_en}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/wlast_done}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arvalid_ready}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/araddr_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arlen_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/arsize_s}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/r_addr}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/r_beat_cnt}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/r_beat_cnt_en}
add wave -noupdate -group axi_slave_3 {/axi_top_1m3s_tb/dut/gen_slaves[0]/u_slave/mem_rd_data}
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/aclk
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/aresetn
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awaddr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awlen
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awburst
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awsize
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awvalid
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wdata
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wstrb
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wlast
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wvalid
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/bresp
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/bvalid
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/bready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/araddr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arlen
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arburst
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arsize
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arvalid
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rdata
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rresp
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rlast
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rvalid
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/start_wr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_addr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_len
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_burst
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_size
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_push
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_push_data
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wr_fifo_full
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/tx_done
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/tx_resp
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/start_rd
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_addr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_len
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_burst
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_size
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_pop
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_pop_data
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rd_fifo_empty
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rx_done
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awvalid_ready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awlength_w
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awburst_w
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/awsize_w
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wfifo_rd_data
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wfifo_empty
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wfifo_rd_en
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/w_beat_cnt
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/w_beat_cnt_en
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wlast_done
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/w_beat_addr
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/wstrb_computed
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/arvalid_ready
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rfifo_wr_data
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rfifo_wr_en
add wave -noupdate -group axi_master /axi_top_1m3s_tb/dut/u_master/rfifo_full
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/aclk
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/aresetn
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awaddr
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awlen
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awburst
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awsize
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awvalid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_awready
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_wdata
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_wstrb
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_wlast
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_wvalid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_wready
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_bresp
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_bvalid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_bready
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_araddr
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_arlen
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_arburst
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_arsize
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_arvalid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_arready
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_rdata
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_rresp
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_rlast
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_rvalid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/m_rready
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/awsel_decode
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/awsel_valid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/slave_sel_wr
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/wr_busy
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/arsel_decode
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/arsel_valid
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/slave_sel_rd
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/rd_busy
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/awsel_active
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/arsel_active
add wave -noupdate -group axi_interconnect /axi_top_1m3s_tb/dut/u_interconnect/i
add wave -noupdate -group tb /axi_top_1m3s_tb/aclk
add wave -noupdate -group tb /axi_top_1m3s_tb/aresetn
add wave -noupdate -group tb /axi_top_1m3s_tb/start_wr
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_addr
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_len
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_burst
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_size
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_push
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_push_data
add wave -noupdate -group tb /axi_top_1m3s_tb/wr_fifo_full
add wave -noupdate -group tb /axi_top_1m3s_tb/tx_done
add wave -noupdate -group tb /axi_top_1m3s_tb/tx_resp
add wave -noupdate -group tb /axi_top_1m3s_tb/start_rd
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_addr
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_len
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_burst
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_size
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_pop
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_pop_data
add wave -noupdate -group tb /axi_top_1m3s_tb/rd_fifo_empty
add wave -noupdate -group tb /axi_top_1m3s_tb/rx_done
add wave -noupdate -group tb /axi_top_1m3s_tb/errors
add wave -noupdate -group tb /axi_top_1m3s_tb/test_count
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2906 ps}
