onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/aclk
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/aresetn
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/start_wr
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_addr
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_len
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_burst
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_size
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_id
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_aw_fifo_full
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_push
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_push_data
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_fifo_full
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/tx_done
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/tx_done_id
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/tx_resp
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/wr_outstanding_cnt
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/start_rd
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_addr
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_len
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_burst
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_size
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_id
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_ar_fifo_full
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_pop
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_pop_data
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rd_fifo_empty
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rx_done
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/rx_done_id
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/errors
add wave -noupdate -group AXI_TOP_TB /axi_top_tb/test_count
add wave -noupdate -group DUT /axi_top_tb/dut/aclk
add wave -noupdate -group DUT /axi_top_tb/dut/aresetn
add wave -noupdate -group DUT /axi_top_tb/dut/start_wr
add wave -noupdate -group DUT /axi_top_tb/dut/wr_addr
add wave -noupdate -group DUT /axi_top_tb/dut/wr_len
add wave -noupdate -group DUT /axi_top_tb/dut/wr_burst
add wave -noupdate -group DUT /axi_top_tb/dut/wr_size
add wave -noupdate -group DUT /axi_top_tb/dut/wr_push
add wave -noupdate -group DUT /axi_top_tb/dut/wr_push_data
add wave -noupdate -group DUT /axi_top_tb/dut/wr_fifo_full
add wave -noupdate -group DUT /axi_top_tb/dut/tx_done
add wave -noupdate -group DUT /axi_top_tb/dut/tx_resp
add wave -noupdate -group DUT /axi_top_tb/dut/start_rd
add wave -noupdate -group DUT /axi_top_tb/dut/rd_addr
add wave -noupdate -group DUT /axi_top_tb/dut/rd_len
add wave -noupdate -group DUT /axi_top_tb/dut/rd_burst
add wave -noupdate -group DUT /axi_top_tb/dut/rd_size
add wave -noupdate -group DUT /axi_top_tb/dut/rd_pop
add wave -noupdate -group DUT /axi_top_tb/dut/rd_pop_data
add wave -noupdate -group DUT /axi_top_tb/dut/rd_fifo_empty
add wave -noupdate -group DUT /axi_top_tb/dut/rx_done
add wave -noupdate -group DUT /axi_top_tb/dut/awaddr
add wave -noupdate -group DUT /axi_top_tb/dut/awlen
add wave -noupdate -group DUT /axi_top_tb/dut/awburst
add wave -noupdate -group DUT /axi_top_tb/dut/awsize
add wave -noupdate -group DUT /axi_top_tb/dut/awvalid
add wave -noupdate -group DUT /axi_top_tb/dut/awready
add wave -noupdate -group DUT /axi_top_tb/dut/wdata
add wave -noupdate -group DUT /axi_top_tb/dut/wstrb
add wave -noupdate -group DUT /axi_top_tb/dut/wlast
add wave -noupdate -group DUT /axi_top_tb/dut/wvalid
add wave -noupdate -group DUT /axi_top_tb/dut/wready
add wave -noupdate -group DUT /axi_top_tb/dut/bresp
add wave -noupdate -group DUT /axi_top_tb/dut/bvalid
add wave -noupdate -group DUT /axi_top_tb/dut/bready
add wave -noupdate -group DUT /axi_top_tb/dut/araddr
add wave -noupdate -group DUT /axi_top_tb/dut/arlen
add wave -noupdate -group DUT /axi_top_tb/dut/arburst
add wave -noupdate -group DUT /axi_top_tb/dut/arsize
add wave -noupdate -group DUT /axi_top_tb/dut/arvalid
add wave -noupdate -group DUT /axi_top_tb/dut/arready
add wave -noupdate -group DUT /axi_top_tb/dut/rdata
add wave -noupdate -group DUT /axi_top_tb/dut/rresp
add wave -noupdate -group DUT /axi_top_tb/dut/rlast
add wave -noupdate -group DUT /axi_top_tb/dut/rvalid
add wave -noupdate -group DUT /axi_top_tb/dut/rready
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/aclk
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/aresetn
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/wr_addr
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/wr_data
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/wr_strb
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/wr_en
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/rd_addr
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/rd_data
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/wr_data_merged
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/i
add wave -noupdate -group s_mem /axi_top_tb/dut/u_slave/u_mem/mem
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/aclk
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/aresetn
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/start
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_in
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/len_in
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/burst_in
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/size_in
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt_en
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_out
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/size_bytes
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/wrap_boundary
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/wrap_base
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_reg
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/burst_reg
add wave -noupdate -group Slave_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt_reg
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/aclk
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/aresetn
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awready
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/addr_in
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/len_in
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/burst_in
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/size_in
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/id_in
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/start_tx
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awaddr
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awlen
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awburst
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awsize
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awid
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awvalid
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awvalid_ready
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awlength_out
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awburst_out
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awsize_out
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/awid_out
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/aw_fifo_full
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/wr_ptr
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/rd_ptr
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/count
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/push
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/pop
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/fifo_empty
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/cs
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/ns
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/addr_reg
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/len_reg
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/burst_reg
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/size_reg
add wave -noupdate -group M_aw_ch /axi_top_tb/dut/u_master/u_aw_ch/id_reg
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/aclk
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/aresetn
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/wr_en
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/wr_data
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/rd_en
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/rd_data
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/full
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/empty
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/wr_ptr
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/rd_ptr
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/count
add wave -noupdate -group M_write_fifo /axi_top_tb/dut/u_master/u_wfifo/i
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/aclk
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/aresetn
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/start
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/addr_in
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/len_in
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/burst_in
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/size_in
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/beat_cnt_en
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/addr_out
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/beat_cnt
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/size_bytes
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/wrap_boundary
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/wrap_base
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/addr_reg
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/burst_reg
add wave -noupdate -group M_beat_gen /axi_top_tb/dut/u_master/u_w_beat_gen/beat_cnt_reg
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/beat_addr
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/size_in
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/wstrb
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/size_bytes
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/lower_byte_lane
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/upper_byte_lane
add wave -noupdate -group M_strb_gen /axi_top_tb/dut/u_master/u_wstrb_gen/i
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/aclk
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/aresetn
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wready
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/awvalid_ready
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/awlength
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/awburst
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wstrb_in
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wdata
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wvalid
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wstrb
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wlast
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/fifo_rd_data
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/fifo_empty
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/fifo_rd_en
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/beat_cnt
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/beat_cnt_en
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/wr_ptr
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/rd_ptr
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/count
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/push
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/pop
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/job_fifo_empty
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/cs
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/ns
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/awlength_reg
add wave -noupdate -group M_w_ch /axi_top_tb/dut/u_master/u_w_ch/awburst_reg
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/aclk
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/aresetn
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/bvalid
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/bresp
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/bid
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/wlast_done
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/bready
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/tx_done
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/tx_done_id
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/bresp_out
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/outstanding_cnt
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/cnt
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/push
add wave -noupdate -group M_B_ch /axi_top_tb/dut/u_master/u_b_ch/pop
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/aclk
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/aresetn
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arready
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/addr_in
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/len_in
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/burst_in
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/size_in
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/id_in
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/start_tx
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/araddr
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arlen
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arburst
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arsize
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arid
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arvalid
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arvalid_ready
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arlength_out
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arburst_out
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arsize_out
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/arid_out
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/ar_fifo_full
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/wr_ptr
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/rd_ptr
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/count
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/push
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/pop
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/fifo_empty
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/cs
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/ns
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/addr_reg
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/len_reg
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/burst_reg
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/size_reg
add wave -noupdate -group M_AR_ch /axi_top_tb/dut/u_master/u_ar_ch/id_reg
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/aclk
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/aresetn
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rvalid
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rdata
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rresp
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rlast
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rid
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/arvalid_ready
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rready
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/fifo_wr_data
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/fifo_wr_en
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/fifo_full
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rx_done
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rx_done_id
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/cs
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/ns
add wave -noupdate -group M_R_ch /axi_top_tb/dut/u_master/u_r_ch/rid_reg
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/aclk
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/aresetn
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/wr_en
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/wr_data
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/rd_en
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/rd_data
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/full
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/empty
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/wr_ptr
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/rd_ptr
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/count
add wave -noupdate -group M_read_fifo /axi_top_tb/dut/u_master/u_rfifo/i
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/aclk
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/aresetn
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awvalid
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awaddr
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awlen
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awburst
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awsize
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awid
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awready
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awvalid_ready
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awaddr_out
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awlen_out
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awburst_out
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awsize_out
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/awid_out
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/wr_ptr
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/rd_ptr
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/count
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/push
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/pop
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/fifo_empty
add wave -noupdate -group S_AW_ch /axi_top_tb/dut/u_slave/u_aw_ch/fifo_full
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/aclk
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/aresetn
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/start
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_in
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/len_in
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/burst_in
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/size_in
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt_en
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_out
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/size_bytes
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/wrap_boundary
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/wrap_base
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_reg
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/burst_reg
add wave -noupdate -group S_write_address_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt_reg
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/aclk
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/aresetn
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wvalid
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wdata
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wstrb
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wlast
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/awvalid_ready
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/awlength
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/awid
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wready
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/mem_wr_data
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/mem_wr_strb
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/mem_wr_en
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/mem_full
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wlast_done
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wlast_done_id
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/wr_ptr
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/rd_ptr
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/count
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/push
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/pop
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/job_fifo_empty
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/cs
add wave -noupdate -group S_W_ch /axi_top_tb/dut/u_slave/u_w_ch/ns
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/aclk
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/aresetn
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/bready
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/wlast_done
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/wlast_done_id
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/bresp_in
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/bvalid
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/bresp
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/bid
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/wr_ptr
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/rd_ptr
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/cnt
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/push
add wave -noupdate -group S_B_ch /axi_top_tb/dut/u_slave/u_b_ch/pop
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/aclk
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/aresetn
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arvalid
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/araddr
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arlen
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arburst
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arsize
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arid
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arready
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/ar_pop
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arvalid_ready
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/araddr_out
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arlen_out
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arburst_out
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arsize_out
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/arid_out
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/wr_ptr
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/rd_ptr
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/count
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/push
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/pop
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/fifo_empty
add wave -noupdate -group S_AR_ch /axi_top_tb/dut/u_slave/u_ar_ch/fifo_full
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/aclk
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/aresetn
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/start
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_in
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/len_in
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/burst_in
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/size_in
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt_en
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_out
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/size_bytes
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/wrap_boundary
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/wrap_base
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/addr_reg
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/burst_reg
add wave -noupdate -group S_read_address_gen /axi_top_tb/dut/u_slave/u_r_addr_gen/beat_cnt_reg
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/aclk
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/aresetn
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rready
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/arvalid_ready
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/beat_cnt
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/arlen
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/arid
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/mem_rd_data
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/mem_rd_valid
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/mem_rd_en
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rdata
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rresp
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rlast
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rid
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/rvalid
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/ar_pop
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/cs
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/ns
add wave -noupdate -group S_R_ch /axi_top_tb/dut/u_slave/u_r_ch/id_reg
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/aclk
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/aresetn
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_addr
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_data
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_strb
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_en
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/rd_addr
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/rd_en
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/rd_data
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/rd_valid
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_index
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/rd_index
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_data_merged
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/i
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/b
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/p
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/mem
add wave -noupdate -group S_mem /axi_top_tb/dut/u_slave/u_mem/wr_index
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/aclk
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/aresetn
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/start
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_in
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/len_in
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/burst_in
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/size_in
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt_en
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_out
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/size_bytes
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/wrap_boundary
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/wrap_base
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/addr_reg
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/burst_reg
add wave -noupdate -group S_write_add_gen /axi_top_tb/dut/u_slave/u_w_addr_gen/beat_cnt_reg
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/aclk
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/aresetn
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/wready
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/wdata
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/wvalid
add wave -noupdate -group WRITE_CHANNEL -radix binary /axi_top_tb/dut/u_master/u_w_ch/wstrb
add wave -noupdate -group WRITE_CHANNEL /axi_top_tb/dut/u_master/u_w_ch/wlast
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/aclk
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/aresetn
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awready
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awaddr
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awlen
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awburst
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awsize
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awid
add wave -noupdate -group AW_CHANNEL /axi_top_tb/dut/u_master/u_aw_ch/awvalid
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/aclk
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/aresetn
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rvalid
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rdata
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rresp
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rlast
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rid
add wave -noupdate -group READ_CHANNEL /axi_top_tb/dut/u_master/u_r_ch/rready
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/aclk
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/aresetn
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arready
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/araddr
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arlen
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arburst
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arsize
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arid
add wave -noupdate -group AR_channel /axi_top_tb/dut/u_master/u_ar_ch/arvalid
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/aclk
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/aresetn
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/bvalid
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/bresp
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/bid
add wave -noupdate -group B_channel /axi_top_tb/dut/u_master/u_b_ch/bready
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {464693 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 212
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {10190 ps} {11695119 ps}
